release:
  github:
    owner: gleich
    name: 'ritcs'
  prerelease: auto
before:
  hooks:
    - go mod download
builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
brews:
  - repository:
      owner: gleich
      name: homebrew-tap
    directory: Formula
    homepage: 'https://github.com/gleich/ritcs'
    description: 'Seamlessly run commands on RIT CS machines with automatic upload, execution, and sync of your local directory.'
    commit_author:
      name: gleich
      email: git@mattglei.ch
    install: bin.install "ritcs"
